routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware'=>'auth','prefix' => 'admin', 'as' => 'admin.','namespace' => 'Admin'],function ()
{


    /***Rojina***/

    Route::get('/', 'DashboardController@dashboard')->name('dashboard');

    Route::resource('/slider','SliderController');
    Route::resource('/component','ComponentController');
    Route::resource('/blog','BlogController');
    Route::resource('/faq','FaqController');
    Route::resource('/career','CareerController');




  /**Sagar***/



    Route::resource('service','ServiceController');
    Route::resource('team','TeamController');



});


Auth::routes();
Auth::routes(['register'=>false ]);

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    protected $fillable =['title','description','status'];
}

app/Http/Controllers/Admin/FaqController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Faq;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faqs=Faq::get();
        return view('backend.faq.index')
            ->with('faqs',$faqs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.faq.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $faq=Faq::create($request->all());
        if($request->hasFile('image'))
        {

            $image =  $request->file('image');
            $imageName =  \Illuminate\Support\Str::random('32') . '.' . $image->getClientOriginalExtension();
            //now save the image file
            $image->move('public/images/faq', $imageName);
            $faq->image = $imageName;
        }
        $faq->save();
        Session::flash('flash_success','Added  Faqs Successfully');
        return redirect(route('admin.faq.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faq=Faq::where('id',$id)->first();
        return view('backend.faq.edit')
            ->with('faq',$faq);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $faq=Faq::find($id);
        $faq->update($request->all());
        if($request->hasFile('image'))
        {
            $image =  $request->file('image');
            $imageName =  \Illuminate\Support\Str::random('32') . '.' . $image->getClientOriginalExtension();
            //now save the image file
            $image->move('public/images/faq', $imageName);
            $faq->image = $imageName;

        }

        $faq->save();
        Session::flash('flash_success','Updated Faqs Successfully');
        return redirect(route('admin.faq.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $faq=Faq::find($id);
        $faq->delete();
        Session::flash('flash_success','Deleted Faqs Successfully');
        return redirect()->back();
    }
}

resources/views/backend/faq/create.blade.php
@extends('backend.layout.app')
@section('main-section')

    <div class="box-header">
        <div class="box-header with-border">
            <section class="content-header">
                <h1>
                    <b>Create Faq</b>
                </h1>


            </section>

        </div>
    </div>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">


                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" class="form-" enctype="multipart/form-data" action="{{route('admin.faq.store')}}">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="hidden" name="_token" value="{{CSRF_token()}}">
                                            <div class="form-group">
                                                <label for="name" class="control-label">Title *</label>
                                                <input type="text" name="title" id="title" class="form-control" required>
                                            </div>

                                            <div class="form-group">
                                                <label for="description" class="control-label">Description</label>
                                                <textarea name="description" id="description" class="form-control" rows="5" required></textarea>
                                            </div>




                                            <div class="form-group">
                                                <label for="status" class="control-label">Status *</label>
                                                <select name="status" class="form-control" required>
                                                    <option value="1">Active</option>
                                                    <option value="0">InActive</option>
                                                </select>
                                            </div>
                                            <div class="box-footer">
                                                <button type="submit" class="btn btn-success">Create</button>
                                                <a href="{{route('admin.faq.index')}}" class="btn btn-danger pull-right">Cancel</a>
                                                <div class="clearfix"></div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


@endsection

resources/views/backend/faq/edit.blade.php
@extends('backend.layout.app')
@section('main-section')

    <div class="box-header">
        <div class="box-header with-border">
            <section class="content-header">
                <h1>
                    <b>Edit Blog</b>
                </h1>


            </section>

        </div>
    </div>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">


                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" class="form-" enctype="multipart/form-data" action="{{route('admin.faq.update',$faq->id)}}">

                                    {{csrf_field()}}
                                    {{method_field("PATCH")}}
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="hidden" name="_token" value="{{CSRF_token()}}">

                                            <div class="form-group">
                                                <label for="name" class="control-label">Title *</label>
                                                <input type="text" name="title" id="title" class="form-control" value="{{$faq->title}}" required>
                                            </div>

                                            <div class="form-group">
                                                <label for="description" class="control-label">Description</label>
                                                <textarea name="description" id="description" class="form-control" rows="5"  required>{{$faq->description}}</textarea>
                                            </div>


                                            <div class="form-group">
                                                <label for="status" class="control-label">Status *</label>
                                                <select class="form-control"  aria-label="Example select with button addon" name="status">
                                                    <option value="1" {{$faq->status==1?'selected':''}}>Active</option>
                                                    <option value="0" {{$faq->status==0?'selected':''}}>Inactive</option>
                                                </select>
                                            </div>
                                            <div class="box-footer">
                                                <button type="submit" class="btn btn-success">Update</button>
                                                <a href="{{route('admin.faq.index')}}" class="btn btn-danger pull-right">Cancel</a>
                                                <div class="clearfix"></div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


@endsection

resources/views/backend/faq/index.blade.php
@extends('backend.layout.app')
@section('main-section')


    <div class="box-header">
        <div class="box-header with-border">
            <section class="content-header">
                <h1>
                    <b>List Faqs</b>
                </h1>

                <div class="col-md-6" style="padding-left: 0px">
                    <div class="col-md-6" style="padding-left: 0px;padding-bottom:5px">
                        <a href="{{route('admin.faq.create')}}" class title="Create">
                                    <span class="badge badge-success">
                                    <i class="fa fa-plus"></i>
                                    </span>
                        </a>
                    </div>
                </div>
            </section>

        </div>
    </div>
    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">

                    <!-- /.box-header -->
                    @if(Session::has('flash'))
                        <div class="alert alert-success">
                            {{Session::get('flash')}}
                        </div>

                    @endif()
                    <div class="box-body">

                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr class="trHighlight">
                                <th>Sn</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th>Action </th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $sn=1;?>
                            @if(count($faqs)>0)
                                @foreach($faqs as $faq)
                                    <tr>
                                        <td>{{$sn}}</td>
                                        <td>{{$faq->title}}</td>
                                        <td>{!!$faq->description!!}</td>
                                        
                                        <td>{{$faq->status==1?"Acitve":"Inactive"}}</td>
                                        <td>
                                            <a href="{{url('admin/faq/'.$faq->id.'/edit')}}" ><i class="fa fa-edit" title="Edit" ></i></a>
                                            |
                                            <form action="{{route('admin.faq.destroy',['faq'=>$faq->id])}}" method="POST" style="display: inline">
                                                {{csrf_field()}}
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-xs btn-danger" onclick="return confirm(' Are You Sure to Delete?')"><i class="fa fa-trash" title="Delete" ></i></button>
                                            </form>


                                        </td>
                                    </tr>
                                    <?php $sn++;?>
                                @endforeach()

                            @endif
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->

@endsection