routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware'=>'auth','prefix' => 'admin', 'as' => 'admin.','namespace' => 'Admin'],function ()
{


    /***Rojina***/

    Route::get('/', 'DashboardController@dashboard')->name('dashboard');

    Route::resource('/slider','SliderController');
    Route::resource('/component','ComponentController');
    Route::resource('/blog','BlogController');
    Route::resource('/faq','FaqController');
    Route::resource('/career','CareerController');




  /**Sagar***/



    Route::resource('service','ServiceController');
    Route::resource('team','TeamController');



});


Auth::routes();
Auth::routes(['register'=>false ]);

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable =['title','slug','image','description','status'];

}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Service;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services=Service::get();
        return view('backend.service.index',compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.service.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $service=Service::create($request->all());
        if($request->hasFile('image'))
        {
            $image =  Input::file('image');
            $imageName =  \Illuminate\Support\Str::random('32') . '.' . $image->getClientOriginalExtension();
            //now save the image file
            $image->move('public/images/service', $imageName);
            $service->image = $imageName;
        }
        $service->save();
        Session::flash('flash_success','Added Successfully');
        return redirect('admin/service');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Service::where('id', $id)->first();
        return view('backend.service.edit')
            ->with('service', $service);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $service = Service::find($id);
        $service->update($request->all());
        if ($request->hasFile('image')) {
            $image =  Input::file('image');
            $imageName =  \Illuminate\Support\Str::random('32') . '.' . $image->getClientOriginalExtension();
            //now save the image file
            $image->move('public/images/service', $imageName);
            $service->image = $imageName;
        }
        $service->save();
        Session::flash('flash', 'Service Updated Successfully');
        return redirect('admin/service');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Service::find($id);
        $service->delete();
        Session::flash('flash', 'Deleted Successfully');
        return redirect('admin/service');
    }
}

resources/views/backend/service/create.blade.php
@extends('backend.layout.app')
@section('main-section')



    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">


                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" class="form-" enctype="multipart/form-data" action="{{route('admin.service.store')}}">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="hidden" name="_token" value="{{CSRF_token()}}">
                                            <div class="form-group">
                                                <label for="name" class="control-label">Title *</label>
                                                <input type="text" name="title" id="title" class="form-control" required>
                                            </div>
                                            <div class="form-group">
                                                <label for="name" class="control-label">Slug * </label><small style="color: red">Please enter the same as title except special characters</small>
                                                <input type="text" name="slug" id="title" class="form-control" required>
                                            </div>



                                            <div class="form-group">
                                                <label for="" class="control-label col-md-2">Image *</label>
                                                <input type="file" name="image" id="image" class="form-control " required>
                                                <small style="color: red">Please upload the image of size 585 x 454 px</small>
                                            </div>

                                            <div class="form-group">
                                                <label for="description" class="control-label">Description</label>
                                                <textarea name="description" id="description" class="form-control" rows="5" required></textarea>
                                            </div>

                                            <div class="form-group">
                                                <label for="status" class="control-label">Status *</label>
                                                <select name="status" class="form-control" required>
                                                    <option value="1">Active</option>
                                                    <option value="0">InActive</option>
                                                </select>
                                            </div>
                                            <div class="box-footer">
                                                <button type="submit" class="btn btn-success">Create</button>
                                                <a href="{{route('admin.service.index')}}" class="btn btn-danger pull-right">Cancel</a>
                                                <div class="clearfix"></div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


@endsection

resources/views/backend/service/edit.blade.php
@extends('backend.layout.app')
@section('main-section')
    <div class="content">
        <div class="col-xs-12">

            <div class="box">

                <div class="box-header">
                    <div class="box-header with-border">
                        <section class="content-header">
                            <h1>
                                <b>Edit Services</b>
                            </h1>
                        </section>
                        <a href="{{route('admin.service.create')}}" class="pull-right" title="Create">
                                    <span class="badge badge-success">
                                    <i class="fa fa-plus"></i>
                                    </span>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <form role="form" method="post" action="{{ route('admin.service.update',$service->id) }}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        {{method_field("PATCH")}}


                            <div class="row">
                                <div class="col-md-12">
                                    <input type="hidden" name="_token" value="{{CSRF_token()}}">
                                    <div class="form-group">
                                        <label for="name" class="control-label">Title *</label>
                                        <input type="text" name="title" id="title" class="form-control" value="{{ $service->title }}" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="name" class="control-label">Slug * </label><small style="color: red">Please enter the same as title except special characters</small>
                                        <input type="text" name="slug" id="title" class="form-control" value="{{ $service->slug }}" required>
                                    </div>



                                    <div class="form-group">
                                        <label for="" class="control-label col-md-2">Image *</label>
                                        <input type="file" name="image" id="image" class="form-control " required>
                                        <small style="color: red">Please upload the image of size 585 x 454 px</small>
                                    </div>

                                    <div class="form-group">
                                        <label for="description" class="control-label">Description</label>
                                        <textarea name="description" id="description" class="form-control" rows="5" required>
                                            {!!  $service->description !!}
                                        </textarea>
                                    </div>

                                    <div class="form-group">
                                        <label for="status" class="control-label">Status *</label>
                                        <select name="status" class="form-control" required>
                                            <option value="1" {{ $service->status==1??'selected' }}>Active</option>
                                            <option value="0" {{ $service->status==0??'selected' }}>InActive</option>
                                        </select>
                                    </div>
                                    <div class="box-footer">
                                        <button type="submit" class="btn btn-success">update</button>
                                        <a href="{{route('admin.service.index')}}" class="btn btn-danger pull-right">Cancel</a>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>


                    </form>
                </div>
            </div>
        </div>
    </div>










@endsection

resources/views/backend/service/index.blade.php
@extends('backend.layout.app')
@section('main-section')



    <div class="box-header">
        <div class="box-header with-border">
            <section class="content-header">
                <h1>
                    <b>List Service</b>
                </h1>

                <div class="col-md-6" style="padding-left: 0px">
                    <div class="col-md-6" style="padding-left: 0px;padding-bottom:5px">
                        <a href="{{route('admin.service.create')}}" class title="Create">
                                    <span class="badge badge-success">
                                    <i class="fa fa-plus"></i>
                                    </span>
                        </a>
                    </div>
                </div>
            </section>

        </div>
    </div>
    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">

                    <!-- /.box-header -->
                    @if(Session::has('flash'))
                        <div class="alert alert-success">
                            {{Session::get('flash')}}
                        </div>

                    @endif()
                    <div class="box-body">

                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr class="trHighlight">
                                <th>Sn</th>
                                <th>Title</th>
                                <th>Slug</th>
                                <th>Image</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th>Action </th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $sn=1;?>
                            @if(count($services)>0)
                                @foreach($services as $serv)
                                    <tr>
                                        <td>{{$sn}}</td>
                                        <td>{{$serv->title}}</td>
                                        <td>{{$serv->slug}}</td>
                                        <td><img src="{{asset('public/images/service/'.$serv->image)}}" alt="" class="img img-responsive" style="width:200px"> </td>
                                        <td>{!!$serv->description!!}</td>
                                        <td>{{$serv->status==1?"Active":"Inactive"}}</td>
                                        <td>
                                            <a href="{{url('admin/service/'.$serv->id.'/edit')}}" ><i class="fa fa-edit" title="Edit" ></i></a>
                                            |
                                            <form action="{{route('admin.service.destroy',['slider'=>$serv->id])}}" method="POST" style="display: inline">
                                                {{csrf_field()}}
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-danger btn-xs" onclick="return confirm(' Are You Sure to Delete?')"><i class="fa fa-trash" title="Delete" ></i></button>
                                            </form>


                                        </td>
                                    </tr>
                                    <?php $sn++;?>
                                @endforeach()

                                @endif
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->

@endsection